const membranePath=[{x:.28,y:.48},{x:.36,y:.45},{x:.45,y:.49},{x:.54,y:.46},{x:.63,y:.5}]

const labels=(scope,text)=>scope.locator('label').filter({hasText:text})
async function addMoleculeDraft(a,name) {
  await a.openProteinSetup()
  await a.page.locator('.molecule-library textarea').fill(name)
  await a.page.getByRole('button',{name:/Add unclassified molecules/}).click()
  await a.page.locator('.molecule-identity').filter({hasText:name}).waitFor()
}
async function configureAntibody(a,name,format,preset) {
  await addMoleculeDraft(a,name)
  const identity=a.page.locator('.identity-fields')
  await labels(identity,'Entity Class').locator('select').selectOption('antibody')
  await labels(identity,'Topology').locator('select').selectOption('soluble')
  await identity.locator('label.topology-confirm input').check()
  const architecture=a.page.locator('.architecture-grid')
  await labels(architecture,'Antibody format').locator('select').selectOption(format)
  if(preset) await labels(architecture,'Valency preset').locator('select').selectOption(preset)
  await a.page.getByRole('button',{name:/Save Molecule/}).click()
  await a.page.waitForTimeout(180)
  return a.qaState('getMoleculeDefinition',name)
}

export const deterministicScenarios=[
  {id:'TC_WORKSPACE_001',title:'Create empty 16:9 workspace',tags:['workspace','smoke','critical'],critical:true,severity:'CRITICAL',component:'Workspace',run:async(a,r)=>{
    await a.step(r,'Start empty canvas',()=>a.startEmpty()); const workspace=await a.qaState('getWorkspace'); const objects=await a.qaState('getSceneObjects')
    a.assert(r,'Workspace exists',!!workspace,true,!!workspace); a.assert(r,'Workspace width',workspace.width===1600,1600,workspace.width); a.assert(r,'Workspace height',workspace.height===900,900,workspace.height); a.assert(r,'Empty scene has no objects',objects.length===0,0,objects.length)
  }},
  {id:'TC_WORKSPACE_002',title:'Resize workspace and restore autosave',tags:['workspace','full','critical'],critical:true,severity:'CRITICAL',component:'Workspace persistence',run:async(a,r)=>{
    await a.startEmpty(); await a.page.getByTestId('workspace-settings').click(); await a.page.locator('.workspace-setup-body > label').filter({hasText:'Preset'}).locator('select').selectOption('presentation_4_3'); await a.page.getByRole('button',{name:/Create \/ Resize Workspace/}).click(); await a.page.waitForTimeout(500); let workspace=await a.qaState('getWorkspace'); a.assert(r,'4:3 dimensions applied',workspace.width===1200&&workspace.height===900,'1200x900',`${workspace.width}x${workspace.height}`); await a.page.reload(); await a.waitQa(); workspace=await a.qaState('getWorkspace'); a.assert(r,'Dimensions persist after reload',workspace.width===1200&&workspace.height===900,'1200x900',`${workspace.width}x${workspace.height}`)
  }},
  {id:'TC_MEMBRANE_001',title:'Draw membrane through toolbar',tags:['membrane','smoke','critical'],critical:true,severity:'MAJOR',component:'Membrane drawing',run:async(a,r)=>{
    await a.startEmpty(); await a.step(r,'Draw freehand membrane',()=>a.drawMembrane(membranePath)); const membranes=await a.qaState('getMembranes'); a.assert(r,'One membrane created',membranes.length===1,1,membranes.length); a.assert(r,'Membrane geometry recorded',membranes[0]?.data?.membrane?.path?.length>=3,'at least 3 points',membranes[0]?.data?.membrane?.path?.length)
  }},
  {id:'TC_MEMBRANE_002',title:'Delete, undo, and redo membrane',tags:['membrane','undo','redo','smoke','critical'],critical:true,severity:'MAJOR',component:'History and membrane deletion',run:async(a,r)=>{
    await a.startEmpty(); await a.drawMembrane(membranePath); const [membrane]=await a.qaState('getMembranes'); await a.step(r,'Select membrane',()=>a.selectObject(membrane.id)); await a.step(r,'Delete membrane',()=>a.deleteSelected()); let count=(await a.qaState('getMembranes')).length; a.assert(r,'Delete removes membrane',count===0,0,count); await a.step(r,'Undo deletion',()=>a.undo()); count=(await a.qaState('getMembranes')).length; a.assert(r,'Undo restores membrane',count===1,1,count); await a.step(r,'Redo deletion',()=>a.redo()); count=(await a.qaState('getMembranes')).length; a.assert(r,'Redo removes membrane again',count===0,0,count)
  }},
  {id:'TC_MEMBRANE_003',title:'Draw consecutive membranes',tags:['membrane','full'],severity:'MAJOR',component:'Membrane drawing',run:async(a,r)=>{
    await a.startEmpty(); await a.drawMembrane(membranePath); await a.drawMembrane(membranePath.map((point)=>({...point,y:point.y+.18}))); const count=(await a.qaState('getMembranes')).length; a.assert(r,'Both membranes remain',count===2,2,count); a.assert(r,'Membrane tool remains available',await a.page.getByTestId('tool-freehand_membrane').isVisible(),true,true)
  }},
  {id:'TC_MEMBRANE_004',title:'Edit an existing membrane path',tags:['membrane','full'],severity:'MAJOR',component:'Membrane path editor',run:async(a,r)=>{
    await a.startEmpty(); await a.drawMembrane([{x:.25,y:.5},{x:.35,y:.39},{x:.45,y:.56},{x:.56,y:.41},{x:.68,y:.52}]); const [membrane]=await a.qaState('getMembranes'); const before=JSON.stringify(membrane.data.membrane.path); await a.selectObject(membrane.id); await a.page.getByRole('button',{name:'Smooth path',exact:true}).click(); await a.page.waitForTimeout(300); const after=JSON.stringify((await a.qaState('getMembranes'))[0].data.membrane.path); a.assert(r,'Smooth path changes geometry',before!==after,'changed membrane path',{before,after})
  }},
  {id:'TC_EDIT_001',title:'Create and drag receptor',tags:['editing','full','critical'],critical:true,severity:'MAJOR',component:'Object manipulation',run:async(a,r)=>{
    await a.startEmpty(); await a.addObject('place_receptor',{x:.42,y:.48}); const [object]=await a.qaState('getSceneObjects'); const before={...object.position}; await a.dragObject(object.id,{x:.62,y:.58}); const after=(await a.qaState('getSceneObject',object.id)).position; a.assert(r,'Object coordinates change',before.x!==after.x||before.y!==after.y,'different position',{before,after})
  }},
  {id:'TC_EDIT_002',title:'Duplicate selected object',tags:['editing','full'],severity:'MAJOR',component:'Object manipulation',run:async(a,r)=>{
    await a.startEmpty(); await a.addObject('place_receptor',{x:.45,y:.5}); const [object]=await a.qaState('getSceneObjects'); await a.selectObject(object.id); await a.pressKey('Control+d'); await a.page.waitForTimeout(450); const objects=await a.qaState('getSceneObjects'); a.assert(r,'Duplicate has a new ID',objects.length===2&&new Set(objects.map((item)=>item.id)).size===2,'2 unique IDs',objects.map((item)=>item.id))
  }},
  {id:'TC_EDIT_003',title:'Multi-select and move objects together',tags:['editing','full'],severity:'MAJOR',component:'Object manipulation',run:async(a,r)=>{
    await a.startEmpty(); await a.addObject('place_receptor',{x:.34,y:.38}); await a.addObject('place_ligand',{x:.55,y:.34}); const objects=await a.qaState('getSceneObjects'); const [first,second]=objects; const before=Object.fromEntries(objects.map((item)=>[item.id,{...item.position}])); const firstBox=await a.page.locator(`.react-flow__node[data-id="${first.id}"]`).boundingBox(); const secondBox=await a.page.locator(`.react-flow__node[data-id="${second.id}"]`).boundingBox(); const left=Math.min(firstBox.x,secondBox.x)-18; const top=Math.min(firstBox.y,secondBox.y)-18; const right=Math.max(firstBox.x+firstBox.width,secondBox.x+secondBox.width)+18; const bottom=Math.max(firstBox.y+firstBox.height,secondBox.y+secondBox.height)+18; await a.page.keyboard.down('Shift'); await a.page.mouse.move(left,top); await a.page.mouse.down(); await a.page.mouse.move(right,bottom,{steps:10}); await a.page.mouse.up(); await a.page.keyboard.up('Shift'); await a.page.waitForTimeout(180); const selected=(await a.qaState('getSceneObjects')).filter((item)=>item.selected); a.assert(r,'Box select chooses both objects',selected.length===2,2,selected.map((item)=>item.id)); await a.dragObject(first.id,{x:.48,y:.53}); const after=await a.qaState('getSceneObjects'); const dx1=after.find((item)=>item.id===first.id).position.x-before[first.id].x; const dy1=after.find((item)=>item.id===first.id).position.y-before[first.id].y; const dx2=after.find((item)=>item.id===second.id).position.x-before[second.id].x; const dy2=after.find((item)=>item.id===second.id).position.y-before[second.id].y; a.assert(r,'Relative X distance is maintained',Math.abs(dx1-dx2)<3,'delta difference < 3',{dx1,dx2}); a.assert(r,'Relative Y distance is maintained',Math.abs(dy1-dy2)<3,'delta difference < 3',{dy1,dy2})
  }},
  {id:'TC_PROTEIN_001',title:'IL18 remains unclassified before lookup',tags:['protein','smoke','critical'],critical:true,severity:'MAJOR',component:'Molecule Setup',run:async(a,r)=>{
    await a.startEmpty(); await a.openProteinSetup(); await a.page.locator('.molecule-library textarea').fill('IL18'); await a.page.getByRole('button',{name:/Add unclassified molecules/}).click(); await a.page.waitForTimeout(150); const molecule=await a.qaState('getMoleculeDefinition','IL18'); a.assert(r,'IL18 is not forced to receptor topology',molecule?.topology!=='single_pass_membrane','not single_pass_membrane',molecule?.topology); a.assert(r,'IL18 awaits identity confirmation',molecule?.entityClass==='unknown_custom','unknown_custom',molecule?.entityClass)
  }},
  {id:'TC_PROTEIN_002',title:'IL18RB UniProt lookup suggests a membrane topology',tags:['protein','uniprot','full','critical'],critical:true,severity:'CRITICAL',component:'UniProt lookup',run:async(a,r)=>{
    await a.startEmpty(); await a.page.route('**/functions/v1/bioscene-uniprot',async(route)=>{const body=route.request().postDataJSON(); const base={primaryAccession:'O95256',entryType:'UniProtKB reviewed (Swiss-Prot)',proteinDescription:{recommendedName:{fullName:{value:'Interleukin-18 receptor accessory protein'}}},genes:[{geneName:{value:'IL18RB'}}],organism:{scientificName:'Homo sapiens',taxonId:9606},sequence:{length:599,value:'M'.repeat(599)}}; if(body.action==='search') return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({results:[base]})}); return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({entry:{...base,features:[{type:'Signal',location:{start:{value:1},end:{value:19}}},{type:'Topological domain',description:'Extracellular',location:{start:{value:20},end:{value:356}}},{type:'Transmembrane',location:{start:{value:357},end:{value:377}}},{type:'Topological domain',description:'Cytoplasmic',location:{start:{value:378},end:{value:599}}}]}})})}); await addMoleculeDraft(a,'IL18RB'); const identity=a.page.locator('.identity-fields'); await labels(identity,'Data privacy').locator('select').selectOption('public'); await a.page.getByRole('button',{name:/Lookup UniProt/}).click(); await a.page.locator('.lookup-status.status-enriched').waitFor(); await a.page.getByText('Topology: Single-pass membrane',{exact:false}).waitFor(); await a.page.getByRole('button',{name:'Accept',exact:true}).click(); await a.page.getByRole('button',{name:/Save Molecule/}).click(); const molecule=await a.qaState('getMoleculeDefinition','IL18RB'); a.assert(r,'Lookup imports the public accession',molecule?.uniprotAccession==='O95256','O95256',molecule?.uniprotAccession); a.assert(r,'Accepted topology is single-pass membrane',molecule?.topology==='single_pass_membrane','single_pass_membrane',molecule?.topology); a.assert(r,'Lookup records membrane annotation',molecule?.structuralModel?.topology?.transmembrane===true,true,molecule?.structuralModel?.topology?.transmembrane); await a.page.unroute('**/functions/v1/bioscene-uniprot')
  }},
  {id:'TC_PROTEIN_003',title:'Domain function persists after setup is reopened',tags:['protein','full'],severity:'MAJOR',component:'Molecule Setup persistence',run:async(a,r)=>{
    await a.startEmpty(); await addMoleculeDraft(a,'PublicProtein-A'); const identity=a.page.locator('.identity-fields'); await labels(identity,'Entity Class').locator('select').selectOption('natural_protein'); await labels(identity,'Topology').locator('select').selectOption('soluble'); await identity.locator('label.topology-confirm input').check(); const domain=a.page.locator('.domain-list article').first(); const functionInput=labels(domain,'Function').locator('input'); await functionInput.fill('Binding'); await a.page.waitForTimeout(180); a.assert(r,'Function field accepts edit',await functionInput.inputValue()==='Binding','Binding',await functionInput.inputValue()); await a.page.getByRole('button',{name:/Save Molecule/}).click(); await a.page.getByRole('button',{name:'Close',exact:true}).click(); await a.openProteinSetup(); const molecule=await a.qaState('getMoleculeDefinition','PublicProtein-A'); a.assert(r,'Domain function survives reopen',molecule?.structuralModel?.domains?.[0]?.function==='Binding','Binding',molecule?.structuralModel?.domains?.[0]?.function); a.assert(r,'Reopened field shows saved function',await labels(a.page.locator('.domain-list article').first(),'Function').locator('input').inputValue()==='Binding','Binding',await labels(a.page.locator('.domain-list article').first(),'Function').locator('input').inputValue())
  }},
  {id:'TC_AB_001',title:'Create, save, and place an IgG antibody',tags:['antibody','full'],severity:'MAJOR',component:'Antibody Architecture Builder',run:async(a,r)=>{
    await a.startEmpty(); const molecule=await configureAntibody(a,'TestIgG-A','igg'); await a.page.getByRole('button',{name:/Add to Scene/}).last().click(); await a.page.waitForTimeout(200); const antibodies=(await a.qaState('getSceneObjects')).filter((item)=>item.data.kind==='antibody'); a.assert(r,'IgG format persists',molecule?.architecture?.antibodyFormat==='igg','igg',molecule?.architecture?.antibodyFormat); a.assert(r,'Saved antibody can be placed',antibodies.length===1,1,antibodies.length)
  }},
  {id:'TC_AB_002',title:'Fab has one binding unit',tags:['antibody','full'],severity:'MAJOR',component:'Antibody Architecture Builder',run:async(a,r)=>{
    await a.startEmpty(); const molecule=await configureAntibody(a,'TestFab-A','fab'); const count=molecule?.architecture?.components?.filter((item)=>item.type==='binding_unit').length; a.assert(r,'Fab format persists',molecule?.architecture?.antibodyFormat==='fab','fab',molecule?.architecture?.antibodyFormat); a.assert(r,'Fab has one binding unit',count===1,1,count)
  }},
  {id:'TC_AB_003',title:'scFv metadata persists',tags:['antibody','full'],severity:'MAJOR',component:'Antibody Architecture Builder',run:async(a,r)=>{
    await a.startEmpty(); const molecule=await configureAntibody(a,'TestScFv-A','scfv'); a.assert(r,'scFv format persists',molecule?.architecture?.antibodyFormat==='scfv','scfv',molecule?.architecture?.antibodyFormat); a.assert(r,'scFv orientation persists',molecule?.architecture?.scfvOrientation==='VH-linker-VL','VH-linker-VL',molecule?.architecture?.scfvOrientation)
  }},
  {id:'TC_AB_004',title:'Bispecific 1+1 creates two binding units',tags:['antibody','full'],severity:'MAJOR',component:'Antibody Architecture Builder',run:async(a,r)=>{
    await a.startEmpty(); const molecule=await configureAntibody(a,'TestBispecific-11','bispecific','1+1'); const valencies=molecule?.architecture?.specificities?.map((item)=>item.valency); const count=molecule?.architecture?.components?.filter((item)=>item.type==='binding_unit').length; a.assert(r,'1+1 valency persists',JSON.stringify(valencies)==='[1,1]',[1,1],valencies); a.assert(r,'Two specificity units generated',count===2,2,count)
  }},
  {id:'TC_SAVE_LOAD_001',title:'Save and reload scene JSON',tags:['save','load','smoke','critical'],critical:true,severity:'CRITICAL',component:'Scene serialization',run:async(a,r)=>{
    await a.startEmpty(); await a.addObject('place_receptor',{x:.4,y:.5}); const savedObjects=await a.qaState('getSceneObjects'); const path=await a.step(r,'Download scene JSON',()=>a.saveJson(`${r.id}.json`)); await a.addObject('place_ligand',{x:.65,y:.42}); let count=(await a.qaState('getSceneObjects')).length; a.assert(r,'Scene changed after save',count===2,2,count); await a.step(r,'Load saved JSON',()=>a.loadJson(path)); const restored=await a.qaState('getSceneObjects'); a.assert(r,'Saved object count restored',restored.length===savedObjects.length,savedObjects.length,restored.length); a.assert(r,'Saved object identity restored',restored[0]?.id===savedObjects[0]?.id,savedObjects[0]?.id,restored[0]?.id)
  }},
  {id:'TC_SCENE_001',title:'Scene scope switches preserve semantic state',tags:['scene','full'],severity:'MAJOR',component:'Scene scope',run:async(a,r)=>{
    await a.startEmpty(); await a.addObject('place_receptor',{x:.5,y:.5}); const id=(await a.qaState('getSceneObjects'))[0].id; for(const sceneType of ['ecm_membrane','full_signaling','intracellular','environment']){await a.page.getByLabel('Scene type',{exact:true}).selectOption(sceneType); await a.page.waitForTimeout(120); const view=await a.qaState('getCurrentView'); a.assert(r,`Scene changes to ${sceneType}`,view.visualizationProfile.sceneType===sceneType,sceneType,view.visualizationProfile.sceneType)} const object=await a.qaState('getSceneObject',id); a.assert(r,'Semantic object survives scene switches',!!object,true,!!object)
  }},
  {id:'TC_AB_005',title:'Save 2+1 bispecific valency',tags:['antibody','full'],severity:'MAJOR',component:'Antibody Architecture Builder',run:async(a,r)=>{
    await a.startEmpty(); await a.openProteinSetup(); await a.page.locator('.molecule-library textarea').fill('TestBispecific-A'); await a.page.getByRole('button',{name:/Add unclassified molecules/}).click(); const identity=a.page.locator('.identity-fields'); await identity.locator('label').filter({hasText:'Entity Class'}).locator('select').selectOption('antibody'); await identity.locator('label').filter({hasText:'Topology'}).locator('select').selectOption('soluble'); await identity.locator('label.topology-confirm input').check(); const architecture=a.page.locator('.architecture-grid'); await architecture.locator('label').filter({hasText:'Antibody format'}).locator('select').selectOption('bispecific'); await architecture.locator('label').filter({hasText:'Valency preset'}).locator('select').selectOption('2+1'); await a.page.getByRole('button',{name:/Save Molecule/}).click(); await a.page.waitForTimeout(200); const molecule=await a.qaState('getMoleculeDefinition','TestBispecific-A'); const valencies=molecule?.architecture?.specificities?.map((item)=>item.valency); a.assert(r,'Bispecific format persists',molecule?.architecture?.antibodyFormat==='bispecific','bispecific',molecule?.architecture?.antibodyFormat); a.assert(r,'2+1 valency persists',JSON.stringify(valencies)==='[2,1]',[2,1],valencies); a.assert(r,'Three binding units generated',molecule?.architecture?.components?.filter((item)=>item.type==='binding_unit').length===3,3,molecule?.architecture?.components?.filter((item)=>item.type==='binding_unit').length)
  }},
  {id:'TC_AB_006',title:'Bispecific 2+2 creates four binding units',tags:['antibody','full'],severity:'MAJOR',component:'Antibody Architecture Builder',run:async(a,r)=>{
    await a.startEmpty(); const molecule=await configureAntibody(a,'TestBispecific-22','bispecific','2+2'); const valencies=molecule?.architecture?.specificities?.map((item)=>item.valency); const count=molecule?.architecture?.components?.filter((item)=>item.type==='binding_unit').length; a.assert(r,'2+2 valency persists',JSON.stringify(valencies)==='[2,2]',[2,2],valencies); a.assert(r,'Four binding units generated',count===4,4,count)
  }},
  {id:'TC_AB_007',title:'Trispecific antibody keeps three specificities',tags:['antibody','full'],severity:'MAJOR',component:'Antibody Architecture Builder',run:async(a,r)=>{
    await a.startEmpty(); const molecule=await configureAntibody(a,'TestTrispecific-A','trispecific'); const specificities=molecule?.architecture?.specificities?.length; const count=molecule?.architecture?.components?.filter((item)=>item.type==='binding_unit').length; a.assert(r,'Trispecific format persists',molecule?.architecture?.antibodyFormat==='trispecific','trispecific',molecule?.architecture?.antibodyFormat); a.assert(r,'Three specificities persist',specificities===3,3,specificities); a.assert(r,'Three binding units generated',count===3,3,count)
  }},
  {id:'TC_COMPARISON_001',title:'Untreated and treated comparison remains paired',tags:['comparison','full'],severity:'MAJOR',component:'Comparison mode',run:async(a,r)=>{
    await a.startEmpty(); const picker=a.page.getByLabel('Mechanism template'); await picker.selectOption('t-cell-activation'); await a.page.waitForTimeout(250); await picker.selectOption('receptor-blockade-comparison'); await a.page.waitForTimeout(450); const objects=await a.qaState('getSceneObjects'); const untreated=objects.filter((item)=>item.data.panelId==='untreated'); const treated=objects.filter((item)=>item.data.panelId==='treated'); const untreatedTargets=new Set(untreated.map((item)=>item.data.target).filter(Boolean)); const shared=treated.filter((item)=>item.data.target&&untreatedTargets.has(item.data.target)); const view=await a.qaState('getCurrentView'); a.assert(r,'Comparison layout is active',view.visualizationProfile.layoutMode==='comparison','comparison',view.visualizationProfile.layoutMode); a.assert(r,'Both comparison panels contain objects',untreated.length>0&&treated.length>0,'objects in both panels',{untreated:untreated.length,treated:treated.length}); a.assert(r,'Common receptor target exists in both panels',shared.length>0,'at least one shared target',shared.map((item)=>item.data.target))
  }},
]
