import { GripVertical, Plus, Trash2 } from 'lucide-react'
import { architectureForFormat, syncArchitecture } from '../molecules'
import type { AntibodyFormat, ConstructArchitecture, ConstructComponentType, MoleculeSpecificity } from '../types'

const formats: { value: AntibodyFormat; label: string }[] = [
  {value:'igg',label:'IgG'},{value:'fab',label:'Fab'},{value:'fab2',label:"F(ab')2"},{value:'scfv',label:'scFv'},{value:'vhh',label:'VHH / nanobody'},{value:'scfv_fc',label:'scFv-Fc'},{value:'fab_fc',label:'Fab-Fc'},{value:'bispecific',label:'Bispecific antibody'},{value:'trispecific',label:'Trispecific antibody'},{value:'multispecific',label:'Multispecific antibody'},{value:'multivalent',label:'Multivalent antibody'},{value:'antibody_fusion',label:'Antibody fusion'},{value:'custom_antibody',label:'Custom antibody architecture'},
]
interface Props { moleculeId:string; value:ConstructArchitecture; onChange:(value:ConstructArchitecture)=>void }

export function AntibodyArchitectureBuilder({moleculeId,value,onChange}:Props) {
  const update=(patch:Partial<ConstructArchitecture>)=>onChange(syncArchitecture(moleculeId,{...value,...patch}))
  const updateSpecificity=(id:string,patch:Partial<MoleculeSpecificity>)=>update({specificities:value.specificities.map((item)=>item.id===id?{...item,...patch}:item)})
  const setPreset=(preset:ConstructArchitecture['valencyPreset'])=>{
    const [a,b]=(preset??'1+1').split('+').map(Number); const items=value.specificities.length>=2?value.specificities:value.specificities.concat({id:'B',label:'Specificity B',target:'',valency:1,unitType:'scFv',function:'Binding'})
    update({valencyPreset:preset,specificities:items.map((item,index)=>index===0?{...item,valency:a}:{...item,valency:index===1?b:item.valency}),symmetry:a===b?'symmetric':'asymmetric'})
  }
  const addSpecificity=(unitType:MoleculeSpecificity['unitType']='Fab')=>{ const index=value.specificities.length; const id=String.fromCharCode(65+Math.min(index,25)); update({specificities:[...value.specificities,{id,label:`Specificity ${id}`,target:'',valency:1,unitType,function:'Binding'}],valencyPreset:'custom'}) }
  const addComponent=(type:ConstructComponentType)=>{ const id=`component:${moleculeId}:custom:${crypto.randomUUID().slice(0,6)}`; update({components:[...value.components,{id,type,label:type.replaceAll('_',' '),order:value.components.length}]}) }
  const move=(source:number,target:number)=>{ const items=[...value.components]; const [item]=items.splice(source,1); items.splice(target,0,item); onChange({...value,components:items.map((entry,index)=>({...entry,order:index}))}) }
  return <section className="architecture-builder">
    <header><div><h3>Antibody Architecture Builder</h3><small>구조·valency·specificity를 diagram 수준에서 정의합니다. 제조법이나 서열 설계 데이터가 아닙니다.</small></div></header>
    <div className="architecture-grid"><label>Antibody format<select value={value.antibodyFormat} onChange={(event)=>onChange(architectureForFormat(moleculeId,event.target.value as AntibodyFormat))}>{formats.map((item)=><option key={item.value} value={item.value}>{item.label}</option>)}</select></label>
      {value.antibodyFormat==='igg'&&<label>IgG subtype<select value={value.iggSubtype} onChange={(event)=>update({iggSubtype:event.target.value as ConstructArchitecture['iggSubtype']})}>{['IgG1','IgG2','IgG3','IgG4','Custom Fc'].map((item)=><option key={item}>{item}</option>)}</select></label>}
      {value.antibodyFormat==='scfv'&&<label>scFv orientation<select value={value.scfvOrientation} onChange={(event)=>update({scfvOrientation:event.target.value as ConstructArchitecture['scfvOrientation']})}><option>VH-linker-VL</option><option>VL-linker-VH</option></select></label>}
      {value.antibodyFormat==='bispecific'&&<label>Valency preset<select value={value.valencyPreset} onChange={(event)=>setPreset(event.target.value as ConstructArchitecture['valencyPreset'])}>{['1+1','2+1','1+2','2+2','custom'].map((item)=><option key={item}>{item}</option>)}</select></label>}
      {['bispecific','trispecific','multispecific','multivalent'].includes(value.antibodyFormat??'')&&<><label>Symmetry<select value={value.symmetry} onChange={(event)=>update({symmetry:event.target.value as ConstructArchitecture['symmetry']})}><option value="symmetric">Symmetric</option><option value="asymmetric">Asymmetric</option><option value="custom">Custom</option></select></label><label>Structural family<select value={value.structuralFamily} onChange={(event)=>update({structuralFamily:event.target.value as ConstructArchitecture['structuralFamily']})}><option value="igg_like">IgG-like bispecific</option><option value="dvd_igg">Dual-variable-domain antibody</option><option value="igg_appended_scfv">IgG + appended scFv</option><option value="cross_arm">Cross-arm / asymmetric IgG</option><option value="tandem_scfv">Tandem scFv</option><option value="fab_scfv_fusion">Fab-scFv fusion</option><option value="vhh_multispecific">VHH-based multispecific</option><option value="fc_multivalent">Fc-based multivalent</option><option value="custom">Custom</option></select></label></>}
      <label className="inline-check"><input type="checkbox" checked={value.fc} onChange={(event)=>update({fc:event.target.checked})}/> Fc present</label>
    </div>
    <div className="specificity-heading"><h4>Specificities &amp; target valency</h4>{['trispecific','multispecific','custom_antibody'].includes(value.antibodyFormat??'')&&<button onClick={()=>addSpecificity()}><Plus size={13}/> Add specificity</button>}</div>
    <div className="specificity-list">{value.specificities.map((item)=><article key={item.id}><strong>{item.label}</strong><label>Target<input value={item.target} onChange={(event)=>updateSpecificity(item.id,{target:event.target.value})}/></label><label>Valency<input type="number" min="1" max="8" value={item.valency} onChange={(event)=>updateSpecificity(item.id,{valency:Math.max(1,Math.min(8,Number(event.target.value)||1))})}/></label><label>Unit<select value={item.unitType} onChange={(event)=>updateSpecificity(item.id,{unitType:event.target.value as MoleculeSpecificity['unitType']})}><option>Fab</option><option>scFv</option><option>VHH</option><option value="protein_domain">Protein domain</option></select></label><label>Function<input value={item.function} onChange={(event)=>updateSpecificity(item.id,{function:event.target.value})}/></label><label>Epitope / domain<input value={item.epitope??''} onChange={(event)=>updateSpecificity(item.id,{epitope:event.target.value})}/></label>{value.specificities.length>1&&<button className="icon-button" onClick={()=>update({specificities:value.specificities.filter((entry)=>entry.id!==item.id),valencyPreset:'custom'})}><Trash2 size={13}/></button>}</article>)}</div>
    <div className="component-tools"><span>+ Component</span>{([['binding_unit','Fab'],['binding_unit','scFv'],['binding_unit','VHH'],['Fc','Fc'],['protein_domain','Protein domain'],['linker','Linker'],['payload','Payload']] as [ConstructComponentType,string][]).map(([type,label])=><button key={`${type}-${label}`} onClick={()=>type==='binding_unit'?addSpecificity(label as MoleculeSpecificity['unitType']):type==='Fc'?update({fc:true}):addComponent(type)}><Plus size={12}/>{label}</button>)}</div>
    <div className="component-tree"><strong>Component tree</strong>{value.components.map((item,index)=><div key={item.id} draggable onDragStart={(event)=>event.dataTransfer.setData('text/plain',String(index))} onDragOver={(event)=>event.preventDefault()} onDrop={(event)=>move(Number(event.dataTransfer.getData('text/plain')),index)}><GripVertical size={13}/><code>{item.label}</code><span>{item.type}{item.target?` → ${item.target}`:''}</span>{!item.id.includes(':custom:')&&<small>{item.attachment}</small>}{item.id.includes(':custom:')&&<button onClick={()=>update({components:value.components.filter((entry)=>entry.id!==item.id)})}><Trash2 size={12}/></button>}</div>)}</div>
  </section>
}

