import { AlertCircle, CheckCircle2, Database, LockKeyhole, Plus, RefreshCw, RotateCcw, Save, ShieldCheck, Trash2, X } from 'lucide-react'
import { useMemo, useRef, useState } from 'react'
import { biologicalFunctionVocabulary, createMolecule, defaultStructuralModel, portsFromDomains } from '../molecules'
import { importUniProtEntry, lookupUniProt, uniProtSpeciesOptions, type UniProtCandidate, type UniProtSpecies, type UniProtStage } from '../uniprot'
import type { DomainDefinition, MoleculeDefinition, StructuralTemplate } from '../types'
import { uid } from '../identity'
import { StructureGlyph } from './StructureGlyph'

interface Props { molecules: MoleculeDefinition[]; customFunctions: string[]; initialMoleculeId?: string; canApply: boolean; onChange: (items: MoleculeDefinition[]) => void; onCustomFunctions: (items: string[]) => void; onApply: (molecule: MoleculeDefinition) => void; onAdd: (molecule: MoleculeDefinition) => void; onClose: () => void }
const templates: StructuralTemplate[] = ['globular','cytokine','enzyme','single_pass_receptor','multi_pass_receptor','gpcr','ion_channel','receptor_complex','igg','fab','fab2','bispecific_igg','asymmetric_bispecific','fc_fusion','receptor_trap','custom_construct']
const stageLabels: Record<UniProtStage,string> = { searching:'Searching UniProt…', fetching:'Fetching annotation…', parsing:'Parsing topology…', building:'Building structure…', matching:'Matching visual template…', done:'Done' }

export function MoleculeSetupPanel(props: Props) {
  const [bulk, setBulk] = useState('IL18\nIL18RA\nIL18RB\nIL4RA\nPDCD1')
  const [selectedId, setSelectedId] = useState(props.initialMoleculeId ?? props.molecules[0]?.id)
  const [busyId, setBusyId] = useState<string>(); const [stage, setStage] = useState<UniProtStage>(); const [species, setSpecies] = useState<UniProtSpecies>('9606')
  const [candidates, setCandidates] = useState<UniProtCandidate[]>([]); const [candidateAccession, setCandidateAccession] = useState(''); const [bulkBusy, setBulkBusy] = useState(false)
  const customFunctionTimer = useRef<number | undefined>(undefined); const selected = props.molecules.find((item) => item.id === selectedId)
  const vocabulary = useMemo(() => Array.from(new Set([...biologicalFunctionVocabulary, ...props.customFunctions])).sort(), [props.customFunctions])
  const replace = (molecule: MoleculeDefinition) => props.onChange(props.molecules.map((item) => item.id === molecule.id ? molecule : item))
  const update = (patch: Partial<MoleculeDefinition>) => selected && replace({ ...selected, ...patch, updatedAt: new Date().toISOString() })
  const updateDomain = (domainId: string, patch: Partial<DomainDefinition>) => selected && update({ structuralModel: { ...selected.structuralModel, modified: true, domains: selected.structuralModel.domains.map((domain) => domain.id === domainId ? { ...domain, ...patch } : domain) } })
  const addBulk = () => { const existing = new Set(props.molecules.map((item) => item.name.toLowerCase())); const additions = bulk.split(/[\n,;]+/).map((item) => item.trim()).filter((item) => item && !existing.has(item.toLowerCase())).map((name) => createMolecule(name, /^(slc[-_]|bispecific|construct|adc)/i.test(name) ? 'private' : 'public')); if (!additions.length) return; props.onChange([...props.molecules, ...additions]); setSelectedId(additions[0].id) }
  const fail = (molecule: MoleculeDefinition, error: unknown) => replace({ ...molecule, lookupStatus:'failed', lookupMessage:error instanceof Error ? error.message : 'UniProt service is temporarily unavailable.', updatedAt:new Date().toISOString() })
  const enrich = async (molecule: MoleculeDefinition) => {
    setBusyId(molecule.id); setCandidates([]); setCandidateAccession(''); setStage('searching'); replace({ ...molecule, lookupStatus:'searching', lookupMessage:stageLabels.searching })
    try { const result = await lookupUniProt(molecule, species, (next) => setStage(next)); if (result.molecule) replace(result.molecule); else { setCandidates(result.candidates); setCandidateAccession(result.candidates[0]?.accession ?? ''); replace({ ...molecule, lookupStatus:'selecting', lookupMessage:'Multiple UniProt entries found. Please select one.' }) } }
    catch (error) { fail(molecule,error) } finally { setBusyId(undefined); setStage(undefined) }
  }
  const importCandidate = async () => { if (!selected || !candidateAccession) return; setBusyId(selected.id); try { const result = await importUniProtEntry(selected,candidateAccession,setStage); replace(result); setCandidates([]); setCandidateAccession('') } catch (error) { fail(selected,error) } finally { setBusyId(undefined); setStage(undefined) } }
  const lookupAll = async () => {
    setBulkBusy(true); let items = [...props.molecules]
    for (const molecule of items.filter((item) => item.privacy === 'public' && item.lookupStatus !== 'enriched')) {
      setBusyId(molecule.id); setSelectedId(molecule.id); try { const result = await lookupUniProt(molecule,species,setStage); const next = result.molecule ?? { ...molecule, lookupStatus:'selecting' as const, lookupMessage:'Multiple UniProt entries found. Open this item to select one.' }; items = items.map((item) => item.id === molecule.id ? next : item); props.onChange(items) } catch (error) { const next = { ...molecule, lookupStatus:'failed' as const, lookupMessage:error instanceof Error ? error.message : 'Lookup failed' }; items = items.map((item) => item.id === molecule.id ? next : item); props.onChange(items) }
    } setBusyId(undefined); setStage(undefined); setBulkBusy(false)
  }
  const manualSetup = () => { if (!selected) return; setCandidates([]); update({ lookupStatus:'suggested', lookupMessage:'Manual structure setup · no external lookup used' }) }
  const resetUniProt = () => selected?.originalStructuralModel && update({ structuralModel: structuredClone(selected.originalStructuralModel), lookupMessage:`Reset to UniProt ${selected.uniprotAccession ?? ''}`.trim() })
  const addCustomFunction = (value: string) => { window.clearTimeout(customFunctionTimer.current); customFunctionTimer.current = window.setTimeout(() => { const term = value.trim(); if (term && !vocabulary.includes(term)) props.onCustomFunctions([...props.customFunctions,term]) },500) }

  return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="Protein and Construct Setup"><section className="molecule-setup-panel">
    <header><div><span className="eyebrow">MOLECULE BUILDER</span><h2>Protein &amp; Construct Setup</h2><p>공개 단백질은 UniProt annotation으로 구조를 만들고, private construct는 외부로 전송하지 않습니다.</p></div><button className="icon-button" onClick={props.onClose} aria-label="Close"><X size={18}/></button></header>
    <div className="molecule-workspace"><aside className="molecule-library">
      <label data-help="단백질·항체·construct 이름을 줄바꿈, 쉼표 또는 세미콜론으로 여러 개 붙여넣으세요. SLC/Custom construct는 기본적으로 Private로 생성되어 외부 조회되지 않습니다.">Protein / construct list<textarea rows={7} value={bulk} onChange={(event) => setBulk(event.target.value)}/></label>
      <button className="wide-action" onClick={addBulk}><Plus size={15}/> Add to project library</button><button className="wide-action secondary" onClick={lookupAll} disabled={bulkBusy}><RefreshCw size={14}/>{bulkBusy ? ' Looking up…' : ' Lookup all public proteins'}</button>
      <h3>My Molecule Library</h3><div className="molecule-list">{props.molecules.map((item) => <button className={item.id === selectedId ? 'selected' : ''} key={item.id} onClick={() => { setSelectedId(item.id); setCandidates([]) }}><span>{item.privacy === 'private' ? <LockKeyhole size={13}/> : item.lookupStatus === 'enriched' ? <CheckCircle2 size={13}/> : item.lookupStatus === 'failed' ? <AlertCircle size={13}/> : <Database size={13}/>}<strong>{item.name}</strong></span><small>{item.structuralModel.template.replaceAll('_',' ')} · {item.lookupStatus}</small></button>)}</div>
    </aside><main className="molecule-editor">{!selected ? <div className="empty-card">왼쪽에서 molecule을 추가하거나 선택하세요.</div> : <>
      <div className="molecule-identity"><div className="molecule-preview"><StructureGlyph data={{ kind:selected.structuralModel.topology.transmembrane?'receptor':selected.moleculeClass==='antibody'?'antibody':'ligand', label:selected.name, compartment:'extracellular', domains:selected.structuralModel.domains, sites:[], ports:[], anchors:[], states:[], allowedCompartments:['extracellular'], structuralModel:selected.structuralModel }}/></div><div><h3>{selected.name}</h3><p>{selected.proteinName ?? 'User-defined biological entity'}</p><span className={`lookup-status status-${selected.lookupStatus}`}>{busyId === selected.id && stage ? stageLabels[stage] : selected.lookupMessage ?? 'Structure is an editable suggestion'}</span>{selected.uniprotAccession && <small className="lookup-meta">{selected.uniprotAccession} · {selected.length ?? '?'} aa · {selected.structuralModel.classification?.replaceAll('_',' ') ?? 'unclassified'}{selected.uniprotCached?' · cached':''}</small>}</div>{selected.privacy === 'public' ? <button data-help="이름·gene symbol·accession을 BioScene 서버에 보내고, 서버가 공식 UniProt REST API를 조회합니다. 여러 후보면 직접 고른 뒤 annotation을 가져옵니다." onClick={() => enrich(selected)} disabled={busyId === selected.id}><RefreshCw size={14}/>{busyId === selected.id?' Working…':' Lookup UniProt'}</button> : <span className="private-badge"><ShieldCheck size={14}/> No external lookup</span>}</div>
      {selected.lookupStatus === 'failed' && <div className="lookup-error"><AlertCircle size={16}/><span>{selected.lookupMessage}</span><button onClick={() => enrich(selected)}>Retry</button><button onClick={manualSetup}>Manual Setup</button></div>}
      {candidates.length > 0 && <section className="candidate-panel"><h3>Select UniProt entry</h3>{candidates.map((item) => <label key={item.accession}><input type="radio" checked={candidateAccession===item.accession} onChange={() => setCandidateAccession(item.accession)}/><span><strong>{item.proteinName}</strong><small>Gene: {item.geneName ?? '—'} · {item.species} · {item.accession} · {item.reviewed?'Reviewed':'Unreviewed'}</small></span></label>)}<button className="primary-button" onClick={importCandidate}>Import selected entry</button></section>}
      <div className="identity-fields"><label>Name<input value={selected.name} onChange={(event) => update({name:event.target.value})}/></label><label>Entity type<select value={selected.privacy} onChange={(event) => update({privacy:event.target.value as 'public'|'private',lookupStatus:event.target.value==='private'?'local':'suggested'})}><option value="public">Public protein</option><option value="private">Private construct</option></select></label><label>Species<select value={species} onChange={(event) => setSpecies(event.target.value as UniProtSpecies)} disabled={selected.privacy==='private'}>{uniProtSpeciesOptions.map((item) => <option value={item.id} key={item.id}>{item.label}</option>)}</select></label><label>Class<select value={selected.moleculeClass} onChange={(event) => { const moleculeClass=event.target.value as MoleculeDefinition['moleculeClass']; update({moleculeClass,structuralModel:defaultStructuralModel(selected.id,selected.name,moleculeClass)}) }}><option value="protein">Protein</option><option value="antibody">Antibody</option><option value="engineered_construct">Engineered construct</option></select></label><label>Visual template<select value={selected.structuralModel.template} onChange={(event) => update({structuralModel:{...selected.structuralModel,template:event.target.value as StructuralTemplate,templateSource:'user',templateConfidence:'confirmed',modified:true}})}>{templates.map((item)=><option key={item} value={item}>{item.replaceAll('_',' ')}</option>)}</select></label><label>UniProt accession<input value={selected.uniprotAccession??''} onChange={(event)=>update({uniprotAccession:event.target.value})} disabled={selected.privacy==='private'}/></label><label>Visual detail<select value={selected.structuralModel.displayLevel} onChange={(event)=>update({structuralModel:{...selected.structuralModel,displayLevel:event.target.value as MoleculeDefinition['structuralModel']['displayLevel'],modified:true}})}><option value="simplified">Simplified</option><option value="named">Domain</option><option value="full">Detailed</option></select></label><label>Visual scaling<select value={selected.structuralModel.visualScaling??'schematic'} onChange={(event)=>update({structuralModel:{...selected.structuralModel,visualScaling:event.target.value as 'schematic'|'sequence_length',modified:true}})}><option value="schematic">Schematic</option><option value="sequence_length">Approximate by sequence length</option></select></label><label>Imported species<input value={selected.species??''} readOnly placeholder="Imported from UniProt"/></label></div>
      <div className="topology-row"><span>Topology</span>{(['extracellular','transmembrane','cytoplasmic'] as const).map((key)=><label key={key}><input type="checkbox" checked={selected.structuralModel.topology[key]} onChange={(event)=>update({structuralModel:{...selected.structuralModel,modified:true,topology:{...selected.structuralModel.topology,[key]:event.target.checked}}})}/>{key}</label>)}{selected.originalStructuralModel && <button onClick={resetUniProt} disabled={!selected.structuralModel.modified}><RotateCcw size={13}/> Reset to UniProt</button>}</div>
      <section className="domain-builder"><div className="domain-heading"><div><h3>Functional domains</h3><small>Domain geometry와 사용자 Function/Target provenance를 분리 저장합니다.</small></div><button onClick={()=>update({structuralModel:{...selected.structuralModel,modified:true,domains:[...selected.structuralModel.domains,{id:`domain:${selected.id}:${uid('custom')}`,label:'New domain',kind:'functional',source:'user',confidence:'confirmed'}]}})}><Plus size={14}/> Domain</button></div><datalist id="function-vocabulary">{vocabulary.map((item)=><option key={item} value={item}/>)}</datalist><div className="domain-list">{selected.structuralModel.domains.map((domain)=><article key={domain.id}><div className="domain-id"><code>{domain.start&&domain.end?`${domain.start}–${domain.end} aa`:domain.id}</code><span>geometry: {domain.source??'user'} · function: {domain.functionSource??'—'} · target: {domain.targetSource??'—'}</span></div><label>Name<input value={domain.label} onChange={(event)=>updateDomain(domain.id,{label:event.target.value,source:'user',confidence:'confirmed'})}/></label><label>Region<select value={domain.kind} onChange={(event)=>updateDomain(domain.id,{kind:event.target.value as DomainDefinition['kind'],source:'user'})}><option value="extracellular">Extracellular</option><option value="transmembrane">Transmembrane</option><option value="intracellular">Cytoplasmic</option><option value="variable">Variable / Fab</option><option value="constant">Constant / Fc</option><option value="functional">Functional</option></select></label><label>Function<input list="function-vocabulary" value={domain.function??''} onChange={(event)=>{updateDomain(domain.id,{function:event.target.value,functionSource:'user'});addCustomFunction(event.target.value)}}/></label><label>Target<input list="molecule-targets" value={domain.target??''} onChange={(event)=>updateDomain(domain.id,{target:event.target.value,targetSource:'user'})}/></label><label>Highlight<input type="checkbox" checked={!!domain.highlighted} onChange={(event)=>updateDomain(domain.id,{highlighted:event.target.checked})}/></label><button className="icon-button" aria-label={`Delete ${domain.label}`} onClick={()=>update({structuralModel:{...selected.structuralModel,modified:true,domains:selected.structuralModel.domains.filter((item)=>item.id!==domain.id)}})}><Trash2 size={14}/></button></article>)}</div><datalist id="molecule-targets">{props.molecules.filter((item)=>item.id!==selected.id).map((item)=><option key={item.id} value={item.name}/>)}</datalist></section>
      <div className="port-preview"><strong>Auto-generated ports</strong>{portsFromDomains(selected).length?portsFromDomains(selected).map((port)=><code key={port.id}>{port.functionalType} → {port.allowedInteractions.join('/')}{port.targetHint?` · ${port.targetHint}`:''}</code>):<small>Domain function을 입력하면 compatible port가 자동 생성됩니다.</small>}</div>
      <footer><button data-help="새 structural cartoon object를 Scene에 추가합니다. 막단백질이고 membrane이 있으면 자동으로 가장 가까운 compatible membrane에 고정됩니다." onClick={()=>props.onAdd(selected)}><Plus size={15}/> Add new instance to Scene</button><button className="primary-button" disabled={!props.canApply} data-help="현재 선택한 캔버스 object에 이 master definition의 구조와 functional port를 연결합니다." onClick={()=>props.onApply(selected)}><Save size={15}/> Update selected instance</button></footer>
    </>}</main></div>
  </section></div>
}
