import { AlertCircle, CheckCircle2, Copy, Database, LockKeyhole, Plus, RefreshCw, Save, ShieldCheck, Trash2, X } from 'lucide-react'
import { useEffect, useMemo, useRef, useState } from 'react'
import { architectureForFormat, biologicalFunctionVocabulary, createMolecule, entityClassLabels, moleculeClassFor, portsFromDomains, structuralModelForMolecule, syncArchitecture, topologyLabels, visualTemplatesForMolecule } from '../molecules'
import { uniProtProvider, type ProteinSearchResult } from '../integrations/uniprot'
import { ProtVistaPanel } from '../integrations/protvista'
import { isUniProtAccession, uniProtSpeciesOptions, type UniProtSpecies, type UniProtStage } from '../uniprot'
import type { BioNodeData, ConstructArchitecture, ConstructComponentType, DomainDefinition, MoleculeDefinition, MoleculeEntityClass, MoleculeOrigin, MoleculeTopology, StructuralTemplate } from '../types'
import { uid } from '../identity'
import { MoleculeRenderer } from './MoleculeRenderer'
import { canLookupUniProt } from '../uniprot'
import { AntibodyArchitectureBuilder } from './AntibodyArchitectureBuilder'

export type MoleculeApplyPolicy='all'|'selected'|'variant'
interface Props { molecules:MoleculeDefinition[]; customFunctions:string[]; initialMoleculeId?:string; canApply:boolean; instanceCounts:Record<string,number>; onChange:(items:MoleculeDefinition[])=>void; onCustomFunctions:(items:string[])=>void; onSave:(molecule:MoleculeDefinition,policy:MoleculeApplyPolicy,variantName?:string)=>void; onDelete:(molecule:MoleculeDefinition,removeInstances:boolean)=>void; onAdd:(molecule:MoleculeDefinition)=>void; onClose:()=>void }
const stages:Record<UniProtStage,string>={searching:'Searching UniProt…',fetching:'Fetching annotation…',parsing:'Parsing topology…',building:'Building structure…',matching:'Matching visual template…',done:'Done'}
const antibodyClasses:MoleculeEntityClass[]=['antibody','adc']
const engineeredClasses:MoleculeEntityClass[]=['antibody','fusion_protein','receptor_trap','adc','protein_drug_conjugate','engineered_protein']
const editableMolecule=(item:MoleculeDefinition)=>structuredClone({...item,privacy:item.privacy==='private'?'private':'public'} as MoleculeDefinition)
const StructureGlyph=({data}:{data:BioNodeData})=><MoleculeRenderer data={data} editorPreview/>

export function MoleculeSetupPanel(props:Props) {
  const [bulk,setBulk]=useState('IL18\nIL18RA\nIL18RB\nSLC-7020\nBispecific-X'); const [selectedId,setSelectedId]=useState(props.initialMoleculeId??props.molecules[0]?.id)
  const selected=props.molecules.find((item)=>item.id===selectedId); const [draft,setDraft]=useState<MoleculeDefinition|undefined>(()=>selected?editableMolecule(selected):undefined); const [dirty,setDirty]=useState(false); const [saveMessage,setSaveMessage]=useState('Saved')
  const [busy,setBusy]=useState(false); const [stage,setStage]=useState<UniProtStage>(); const [species,setSpecies]=useState<UniProtSpecies>('9606'); const [candidates,setCandidates]=useState<ProteinSearchResult[]>([]); const [candidate,setCandidate]=useState(''); const [policy,setPolicy]=useState<MoleculeApplyPolicy>('all'); const [variantName,setVariantName]=useState(''); const timer=useRef<number|undefined>(undefined);
  const vocabulary=useMemo(()=>Array.from(new Set([...biologicalFunctionVocabulary,...props.customFunctions])).sort(),[props.customFunctions])
  useEffect(()=>{ if (!selected||dirty) return; setDraft(editableMolecule(selected)); setSaveMessage(selected.saveStatus==='saved'?'Saved':selected.saveStatus==='unclassified'?'Identity required':'Draft') },[dirty,selected])
  useEffect(()=>{ if (!draft||!dirty) return; setSaveMessage('Unsaved changes…'); window.clearTimeout(timer.current); timer.current=window.setTimeout(()=>{ try { sessionStorage.setItem(`bioscene.molecule.draft:${draft.id}`,JSON.stringify(draft)); setSaveMessage('Draft saved locally') } catch { setSaveMessage('Unsaved changes…') } },350); return()=>window.clearTimeout(timer.current) },[dirty,draft])
  const change=(patch:Partial<MoleculeDefinition>)=>{ setDraft((current)=>current?{...current,...patch,saveStatus:current.entityClass==='unknown_custom'?'unclassified':'draft',updatedAt:new Date().toISOString()}:current); setDirty(true) }
  const replaceDraft=(next:MoleculeDefinition)=>{ setDraft(next); setDirty(true) }
  const rebuild=(next:MoleculeDefinition)=>({...next,moleculeClass:moleculeClassFor(next.entityClass),structuralModel:structuralModelForMolecule(next)})
  const select=(item:MoleculeDefinition)=>{ if (dirty&&!window.confirm('저장되지 않은 molecule 변경을 버리고 다른 항목을 열까요?')) return; setSelectedId(item.id); setDraft(editableMolecule(item)); setDirty(false); setCandidates([]); setSaveMessage(item.saveStatus==='saved'?'Saved':item.saveStatus==='unclassified'?'Identity required':'Draft') }
  const setIdentity=(entityClass:MoleculeEntityClass)=>{ if (!draft) return; const origin:MoleculeOrigin=entityClass==='mutant_protein'?'mutant':engineeredClasses.includes(entityClass)?'engineered':'natural'; const privacy=engineeredClasses.includes(entityClass)?'private':'public'; let architecture=draft.architecture; if (antibodyClasses.includes(entityClass)) architecture=architecture?.kind==='antibody'?architecture:architectureForFormat(draft.id,'igg'); else if (['fusion_protein','receptor_trap','engineered_protein','protein_drug_conjugate'].includes(entityClass)) architecture=architecture?.kind==='fusion'?architecture:{kind:'fusion',fc:entityClass==='receptor_trap',specificities:[],components:[]}; else architecture=undefined; replaceDraft(rebuild({...draft,entityClass,origin,privacy,architecture,identitySource:'user',identityConfidence:'confirmed',saveStatus:'draft'})) }
  const setTopology=(topology:MoleculeTopology)=>draft&&replaceDraft(rebuild({...draft,topology,topologySource:'user',topologyConfidence:'confirmed',topologyConfirmed:true,saveStatus:'draft'}))
  const setAccession=(value:string)=>{ if (!draft) return; const accession=value.trim().toUpperCase(); change({uniprotAccession:accession||undefined,proteinName:undefined,length:undefined,sequence:undefined,uniprotFeatures:undefined,uniprotFetchedAt:undefined,uniprotCached:false,lookupStatus:'local',lookupMessage:accession?(isUniProtAccession(accession)?'Manual accession · reference viewer available; run lookup to import validated annotation':'UniProt accession 형식을 확인하세요.'):'Manual setup'}) }
  const updateDomain=(id:string,patch:Partial<DomainDefinition>)=>draft&&replaceDraft({...draft,structuralModel:{...draft.structuralModel,modified:true,domains:draft.structuralModel.domains.map((item)=>item.id===id?{...item,...patch}:item)}})
  const addBulk=()=>{ const existing=new Set(props.molecules.map((item)=>item.name.toLowerCase())); const additions=bulk.split(/[\n,;]+/).map((item)=>item.trim()).filter((item)=>item&&!existing.has(item.toLowerCase())).map((name)=>createMolecule(name)); if (!additions.length) return; props.onChange([...props.molecules,...additions]); select(additions[0]) }
  const duplicate=(item:MoleculeDefinition)=>{ const copy=structuredClone(item); copy.id=`molecule:${item.name.replace(/[^A-Za-z0-9_-]+/g,'_')}:${crypto.randomUUID().slice(0,8)}`; copy.name=`${item.name} copy`; copy.saveStatus='draft'; copy.savedAt=undefined; if (copy.architecture) copy.architecture=syncArchitecture(copy.id,{...copy.architecture,components:[]}); copy.structuralModel=structuralModelForMolecule(copy); props.onChange([...props.molecules,copy]); select(copy) }
  const remove=(item:MoleculeDefinition)=>{ const count=props.instanceCounts[item.id]??0; if (!count) { if (window.confirm(`${item.name}을 library에서 삭제할까요?`)) props.onDelete(item,false); return } const answer=window.prompt(`이 molecule은 Scene instance ${count}개에서 사용 중입니다.\nLIBRARY = library에서만 제거\nALL = library와 scene에서 모두 제거\nCANCEL = 취소`,'LIBRARY')?.toUpperCase(); if (answer==='LIBRARY') props.onDelete(item,false); if (answer==='ALL') props.onDelete(item,true) }
  const enrich=async()=>{ if (!draft||draft.privacy==='private') return; setBusy(true); setCandidates([]); try { const result=await uniProtProvider.lookupFor(draft,species,setStage); if (result.molecule) replaceDraft(result.molecule); else { setCandidates(result.candidates); setCandidate(result.candidates[0]?.accession??'') } } catch(error) { replaceDraft({...draft,lookupStatus:'failed',lookupMessage:error instanceof Error?error.message:'Lookup failed'}) } finally { setBusy(false); setStage(undefined) } }
  const chooseCandidate=async()=>{ if (!draft||!candidate) return; setBusy(true); try { replaceDraft(await uniProtProvider.importInto(draft,candidate,setStage)); setCandidates([]) } catch(error) { replaceDraft({...draft,lookupStatus:'failed',lookupMessage:error instanceof Error?error.message:'Import failed'}) } finally { setBusy(false); setStage(undefined) } }
  const acceptSuggestions=()=>{ if (!draft) return; const entityClass=draft.suggestedEntityClass??draft.entityClass; const topology=draft.suggestedTopology??draft.topology; replaceDraft(rebuild({...draft,entityClass,origin:'natural',privacy:'public',moleculeClass:moleculeClassFor(entityClass),identitySource:draft.suggestedEntityClass?'UniProt':draft.identitySource,identityConfidence:'high',topology,topologySource:'UniProt',topologyConfidence:'high',topologyConfirmed:true,saveStatus:'draft'})) }
  const save=()=>{ if (!draft||draft.entityClass==='unknown_custom'||!draft.topologyConfirmed) return; const next={...rebuild(draft),saveStatus:'saved' as const,savedAt:new Date().toISOString(),updatedAt:new Date().toISOString()}; props.onSave(next,policy,variantName.trim()||undefined); try { sessionStorage.removeItem(`bioscene.molecule.draft:${draft.id}`) } catch { /* optional */ } setDraft(next); setDirty(false); setSaveMessage('Saved') }
  const close=()=>{ if (!dirty||window.confirm('저장되지 않은 molecule 변경을 버리고 닫을까요?')) props.onClose() }
  const instanceCount=draft?props.instanceCounts[draft.id]??0:0

  return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="Protein and Construct Setup"><section className="molecule-setup-panel identity-overhaul"><header><div><span className="eyebrow">MOLECULE DEFINITION</span><h2>Protein &amp; Construct Setup</h2><p>Name → Identity → Structure → Function → Visual → Save</p></div><div className={`molecule-save-state ${dirty?'dirty':''}`}>{dirty?'● ':''}{saveMessage}</div><button className="icon-button" onClick={close} aria-label="Close"><X size={18}/></button></header>
    <nav className="wizard-steps">{['1 Identity','2 Structure','3 Function','4 Visual','5 Save'].map((item)=><span key={item}>{item}</span>)}</nav><div className="molecule-workspace"><aside className="molecule-library"><label data-help="이름만 입력하면 Unclassified로 추가됩니다. Entity Class와 topology는 자동 확정하지 않으며 사용자가 확인해야 합니다.">Molecule names<textarea rows={6} value={bulk} onChange={(event)=>setBulk(event.target.value)}/></label><button className="wide-action" onClick={addBulk}><Plus size={14}/> Add unclassified molecules</button><h3>My Molecule Library</h3><div className="molecule-list">{props.molecules.map((item)=><article key={item.id} className={item.id===selectedId?'selected':''}><button className="molecule-row" onClick={()=>select(item)}><span>{item.privacy==='private'?<LockKeyhole size={12}/>:<Database size={12}/>}<strong>{item.name}</strong>{item.saveStatus!=='saved'&&<b>●</b>}</span><small>{item.entityClass==='unknown_custom'?'⚠ Unclassified':entityClassLabels[item.entityClass]} · {item.architecture?.antibodyFormat?.replaceAll('_',' ')??topologyLabels[item.topology]}</small></button><div><button title="Edit" onClick={()=>select(item)}>Edit</button><button title="Duplicate" onClick={()=>duplicate(item)}><Copy size={11}/></button><button title="Add to Scene" disabled={item.saveStatus!=='saved'} onClick={()=>props.onAdd(item)}><Plus size={11}/></button><button title="Delete" onClick={()=>remove(item)}><Trash2 size={11}/></button></div></article>)}</div></aside>
      <main className="molecule-editor">{!draft?<div className="empty-card">새 molecule을 추가하거나 library에서 선택하세요.</div>:<>
        <div className="molecule-identity"><div className="molecule-preview"><StructureGlyph data={{kind:antibodyClasses.includes(draft.entityClass)?'antibody':draft.topology.includes('membrane')?'receptor':'ligand',label:draft.name,compartment:'extracellular',domains:draft.structuralModel.domains,sites:[],ports:[],anchors:[],states:[],allowedCompartments:['extracellular'],structuralModel:draft.structuralModel}}/></div><div><h3>{draft.name}</h3><p>{draft.entityClass==='unknown_custom'?'⚠ Identity를 먼저 확인하세요.':`${entityClassLabels[draft.entityClass]} · ${draft.origin} · ${topologyLabels[draft.topology]}`}</p><span className={`lookup-status status-${draft.lookupStatus}`}>{busy&&stage?stages[stage]:draft.lookupMessage??`${draft.saveStatus} molecule definition`}</span><small className="lookup-meta">Identity: {draft.identitySource}{draft.identityConfidence?` / ${draft.identityConfidence}`:''} · Topology: {draft.topologySource??'unconfirmed'}</small>{draft.structuralModel.structureTrace&&<small className="lookup-meta">Structure: <a href={draft.structuralModel.structureTrace.entryUrl} target="_blank" rel="noreferrer">{draft.structuralModel.structureTrace.source} · {draft.structuralModel.structureTrace.modelId}</a></small>}</div>{draft.privacy==='private'?<span className="private-badge"><ShieldCheck size={14}/> Private · no external lookup</span>:<button onClick={enrich} disabled={busy||!canLookupUniProt(draft)} data-help="단백질명·유전자명 또는 UniProt accession으로 공개 서열과 AlphaFold 구조를 조회합니다. 처음 만든 Unknown 항목도 바로 조회할 수 있으며, 항체·융합체 같은 인공 construct는 구성요소별로 조회하세요."><RefreshCw size={14}/>{busy?' Working…':' Lookup UniProt'}</button>}</div>
        {draft.lookupStatus==='failed'&&<div className="lookup-error"><AlertCircle size={15}/><span>{draft.lookupMessage}</span><button onClick={enrich}>Retry</button><button onClick={()=>change({lookupStatus:'local',lookupMessage:'Manual setup'})}>Manual Setup</button></div>}
        {candidates.length>0&&<section className="candidate-panel"><h3>Select UniProt entry</h3>{candidates.map((item)=><label key={item.accession}><input type="radio" checked={candidate===item.accession} onChange={()=>setCandidate(item.accession)}/><span><strong>{item.name}</strong><small>{item.geneName??'—'} · {item.species} · {item.accession}</small></span></label>)}<button className="primary-button" onClick={chooseCandidate}>Import selected entry</button></section>}
        {(draft.suggestedEntityClass||draft.suggestedTopology)&&!draft.topologyConfirmed&&<div className="suggestion-card"><div><strong>System suggestion</strong><span>Entity: {entityClassLabels[draft.suggestedEntityClass??draft.entityClass]}</span><span>Topology: {topologyLabels[draft.suggestedTopology??draft.topology]}</span><small>High confidence · Based on UniProt annotation</small></div><button onClick={acceptSuggestions}><CheckCircle2 size={14}/> Accept</button><button onClick={()=>change({suggestedEntityClass:undefined,suggestedTopology:undefined})}>Change manually</button></div>}
        <section className="identity-section"><h3>1 · Identity</h3><div className="identity-fields"><label>Name<input value={draft.name} onChange={(event)=>change({name:event.target.value})}/></label><label>Entity Class<select value={draft.entityClass} onChange={(event)=>setIdentity(event.target.value as MoleculeEntityClass)}>{Object.entries(entityClassLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Origin<select value={draft.origin} onChange={(event)=>change({origin:event.target.value as MoleculeOrigin,identitySource:'user'})}><option value="natural">Natural</option><option value="engineered">Engineered</option><option value="mutant">Mutant</option><option value="synthetic">Synthetic</option></select></label><label>Data privacy<select value={draft.privacy} onChange={(event)=>change({privacy:event.target.value as 'public'|'private'})}><option value="public">Public entity</option><option value="private">Private / proprietary</option></select></label><label>Topology<select value={draft.topology} onChange={(event)=>setTopology(event.target.value as MoleculeTopology)}>{Object.entries(topologyLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="topology-confirm"><input type="checkbox" checked={draft.topologyConfirmed} onChange={(event)=>replaceDraft({...draft,topologyConfirmed:event.target.checked,topologySource:'user',topologyConfidence:event.target.checked?'confirmed':'low',saveStatus:'draft',updatedAt:new Date().toISOString()})}/> 이 topology를 사용자 확인함</label><label>Species<select value={species} onChange={(event)=>setSpecies(event.target.value as UniProtSpecies)} disabled={draft.privacy==='private'}>{uniProtSpeciesOptions.map((item)=><option value={item.id} key={item.id}>{item.label}</option>)}</select></label>{draft.privacy==='public'&&<label data-help="예: P05067. 공개 UniProt accession을 입력하면 annotation 참고 뷰어를 바로 열 수 있습니다. Lookup을 실행해야 BioScene 구조 데이터로 검증·가져오기 됩니다.">UniProt accession (optional)<input value={draft.uniprotAccession??''} placeholder="e.g. P05067" aria-invalid={!!draft.uniprotAccession&&!isUniProtAccession(draft.uniprotAccession)} onChange={(event)=>setAccession(event.target.value)}/></label>}{draft.entityClass==='mutant_protein'&&<label>Parent protein<select value={draft.parentMoleculeId??''} onChange={(event)=>change({parentMoleculeId:event.target.value})}><option value="">Select parent…</option>{props.molecules.filter((item)=>item.id!==draft.id).map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}</div></section>
        <section className="identity-section"><h3>2 · Structure</h3>{antibodyClasses.includes(draft.entityClass)&&draft.architecture?<AntibodyArchitectureBuilder moleculeId={draft.id} value={draft.architecture} onChange={(architecture)=>replaceDraft(rebuild({...draft,architecture}))}/>:['fusion_protein','receptor_trap','engineered_protein','protein_drug_conjugate'].includes(draft.entityClass)?<GenericConstructBuilder molecule={draft} onChange={(architecture)=>replaceDraft(rebuild({...draft,architecture}))}/>:<><div className="natural-structure"><span>Topology: <b>{topologyLabels[draft.topology]}</b></span><span>Source: <b>{draft.topologySource??'User confirmation required'}</b></span>{draft.uniprotAccession&&<span>UniProt: <b>{draft.uniprotAccession}{draft.length?` · ${draft.length} aa`:''}</b></span>}</div><ProtVistaPanel molecule={draft} onAddDomain={(domain)=>replaceDraft({...draft,saveStatus:'draft',updatedAt:new Date().toISOString(),structuralModel:{...draft.structuralModel,modified:true,domains:[...draft.structuralModel.domains,domain]}})}/></>}</section>
        <section className="domain-builder"><div className="domain-heading"><div><h3>3 · Function</h3><small>구조 provenance와 Function/Target provenance는 별도로 저장됩니다.</small></div><button onClick={()=>change({structuralModel:{...draft.structuralModel,modified:true,domains:[...draft.structuralModel.domains,{id:`domain:${draft.id}:${uid('custom')}`,label:'New domain',kind:'functional',source:'user',confidence:'confirmed'}]}})}><Plus size={13}/> Domain</button></div><datalist id="function-vocabulary">{vocabulary.map((item)=><option key={item} value={item}/>)}</datalist><div className="domain-list">{draft.structuralModel.domains.map((domain)=><article key={domain.id}><div className="domain-id"><code>{domain.start&&domain.end?`${domain.start}–${domain.end} aa`:domain.label}</code><span>geometry: {domain.source??'user'} · function: {domain.functionSource??'—'} · target: {domain.targetSource??'—'}</span></div><label>Name<input value={domain.label} onChange={(event)=>updateDomain(domain.id,{label:event.target.value,source:'user'})}/></label><label>Region<select value={domain.kind} onChange={(event)=>updateDomain(domain.id,{kind:event.target.value as DomainDefinition['kind'],source:'user'})}><option value="extracellular">Extracellular</option><option value="transmembrane">Transmembrane</option><option value="intracellular">Cytoplasmic</option><option value="variable">Variable / binding unit</option><option value="constant">Constant / Fc</option><option value="functional">Functional</option></select></label><label>Function<input list="function-vocabulary" value={domain.function??''} onChange={(event)=>updateDomain(domain.id,{function:event.target.value,functionSource:'user'})}/></label><label>Target<input value={domain.target??''} onChange={(event)=>updateDomain(domain.id,{target:event.target.value,targetSource:'user'})}/></label><label>Highlight<input type="checkbox" checked={!!domain.highlighted} onChange={(event)=>updateDomain(domain.id,{highlighted:event.target.checked})}/></label><button className="icon-button" onClick={()=>change({structuralModel:{...draft.structuralModel,modified:true,domains:draft.structuralModel.domains.filter((item)=>item.id!==domain.id)}})}><Trash2 size={13}/></button></article>)}</div></section>
        <section className="identity-section"><h3>4 · Visual</h3><div className="identity-fields"><label data-help="확정된 molecule identity와 topology에 맞는 그림만 표시됩니다. Single-pass receptor는 한 개 막관통부, multi-pass는 다중 나선, 항체는 Fab/Fc 구조로 삽입됩니다.">Template<select value={draft.structuralModel.template} onChange={(event)=>change({structuralModel:{...draft.structuralModel,template:event.target.value as StructuralTemplate,templateSource:'user',templateConfidence:'confirmed'}})}>{visualTemplatesForMolecule(draft).map((item)=><option key={item}>{item}</option>)}</select></label><label>Detail<select value={draft.structuralModel.displayLevel} onChange={(event)=>change({structuralModel:{...draft.structuralModel,displayLevel:event.target.value as MoleculeDefinition['structuralModel']['displayLevel']}})}><option value="simplified">Simplified</option><option value="named">Domain</option><option value="full">Detailed</option></select></label></div><div className="port-preview"><strong>Generated ports</strong>{portsFromDomains(draft).map((port)=><code key={port.id}>{port.id.split(':').at(-2)} · {port.functionalType} → {port.targetHint||'unassigned'}</code>)}</div></section>
        <section className="save-molecule-section"><div><h3>5 · Save</h3><p>{instanceCount?`This molecule is used in ${instanceCount} scene instance(s).`:'No scene instances currently use this molecule.'}{!draft.topologyConfirmed?' · Topology confirmation is required before save.':''}</p><label><input type="radio" checked={policy==='all'} onChange={()=>setPolicy('all')}/> All scene instances</label><label><input type="radio" checked={policy==='selected'} disabled={!props.canApply} onChange={()=>setPolicy('selected')}/> This instance only</label><label><input type="radio" checked={policy==='variant'} onChange={()=>setPolicy('variant')}/> Save as new variant</label>{policy==='variant'&&<input placeholder={`${draft.name} v2`} value={variantName} onChange={(event)=>setVariantName(event.target.value)}/>}</div><footer><button onClick={close}>Cancel</button><button className="primary-button" disabled={draft.entityClass==='unknown_custom'||!draft.topologyConfirmed||!dirty&&draft.saveStatus==='saved'} onClick={save}><Save size={14}/> Save Molecule</button><button disabled={draft.saveStatus!=='saved'||dirty} onClick={()=>props.onAdd(draft)}><Plus size={14}/> Add to Scene</button></footer></section>
      </>}</main></div></section></div>
}

function GenericConstructBuilder({molecule,onChange}:{molecule:MoleculeDefinition;onChange:(value:ConstructArchitecture)=>void}) {
  const value=molecule.architecture??{kind:'fusion' as const,fc:false,specificities:[],components:[]}; const add=(type:ConstructComponentType)=>{ const components=[...value.components,{id:`component:${molecule.id}:${crypto.randomUUID().slice(0,6)}`,type,label:type.replaceAll('_',' '),order:value.components.length}]; onChange({...value,components}) }; const edit=(id:string,patch:Record<string,string>)=>onChange({...value,components:value.components.map((item)=>item.id===id?{...item,...patch}:item)})
  return <div className="generic-construct"><div className="component-tools">{(['protein_domain','linker','Fc','payload'] as ConstructComponentType[]).map((type)=><button key={type} onClick={()=>add(type)}><Plus size={12}/> {type.replaceAll('_',' ')}</button>)}</div>{value.components.map((item)=><article key={item.id}><strong>{item.order+1}</strong><label>Component<input value={item.label} onChange={(event)=>edit(item.id,{label:event.target.value})}/></label><label>Source protein<input value={item.sourceProtein??''} onChange={(event)=>edit(item.id,{sourceProtein:event.target.value})}/></label><label>Domain<input value={item.domainName??''} onChange={(event)=>edit(item.id,{domainName:event.target.value})}/></label><label>Function<input value={item.function??''} onChange={(event)=>edit(item.id,{function:event.target.value})}/></label><label>Target<input value={item.target??''} onChange={(event)=>edit(item.id,{target:event.target.value})}/></label><button onClick={()=>onChange({...value,components:value.components.filter((entry)=>entry.id!==item.id)})}><Trash2 size={12}/></button></article>)}</div>
}

