import { CheckCircle2, ClipboardCheck, PackageCheck, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import type { ReviewMetadata } from '../types'

export function ReviewPanel({ value, onChange, onClose, onExportPackage }: { value: ReviewMetadata; onChange: (value: ReviewMetadata) => void; onClose: () => void; onExportPackage: () => void }) {
  const [reviewersDraft, setReviewersDraft] = useState(value.reviewers.join(', '))
  useEffect(() => setReviewersDraft(value.reviewers.join(', ')), [value.reviewers])
  const update = (patch: Partial<ReviewMetadata>) => onChange({ ...value, ...patch, updatedAt: new Date().toISOString() })
  return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="Scene review"><section className="review-panel"><header><div><span className="eyebrow">SCIENTIFIC REVIEW</span><h2><ClipboardCheck size={21} /> Review metadata</h2><p>Keep approval state and scientific review notes with the scene.</p></div><button className="icon-button" onClick={onClose} aria-label="Close"><X size={18} /></button></header><div className="review-form"><label data-help="Draft는 작성 중, In review는 과학 검수 중, Approved는 승인 완료를 뜻합니다. 선택값은 상단 상태 버튼과 Scene/리뷰 ZIP 메타데이터에 반영됩니다.">Status<select value={value.status} onChange={(e) => update({ status: e.target.value as ReviewMetadata['status'] })}><option value="draft">Draft</option><option value="in-review">In review</option><option value="approved">Approved</option></select></label><label data-help="검토자 이름·팀·역할을 쉼표로 구분해 입력하세요. 입력란을 벗어나면 각각의 검토자로 저장되어 리뷰 자료에 포함됩니다.">Reviewers<input value={reviewersDraft} onChange={(e) => setReviewersDraft(e.target.value)} onBlur={() => update({ reviewers: reviewersDraft.split(',').map((item) => item.trim()).filter(Boolean) })} placeholder="Name, team, or function" /></label><label data-help="가정, 근거 공백, 수정 요청과 승인 조건을 입력합니다. 장면에는 보이지 않지만 Scene JSON과 REVIEW.md에 보존됩니다.">Scientific review notes<textarea rows={7} value={value.notes} onChange={(e) => update({ notes: e.target.value })} placeholder="Assumptions, evidence gaps, requested changes…" /></label><div className="review-updated"><CheckCircle2 size={15} /> Updated {new Date(value.updatedAt).toLocaleString()}</div><button className="review-package-button" data-help="현재 그림 PNG, 편집 가능한 Scene JSON, 검토 메모, 상호작용 근거 CSV, 문헌·협업·provenance·라이선스 정보를 하나의 ZIP으로 저장합니다." onClick={onExportPackage}><PackageCheck size={16} /> Export review package (.zip)</button></div></section></div>
}
